### ISSUE TITLE
When would you release leaf_gan_model?

### ISSUE THREAD

**Issue by kasim0226** [IyatomiLab/LeafGAN#1]
Hi authors,

Thank you for your great work.
I am curious about when would you release leaf_gan_model?
I saw paper is published, so I am looking forward to seeing the codes.

Looking forward to hearing from you

**Comment by huuquan1994** [comment]
Hi @kasim0226,
Thanks for reaching out! Currently, our paper has been accepted as a regular IEEE transactions paper. Please wait for a few days, we will upload the code and additional documents soon.

**Comment by huuquan1994** [comment]
@kasim0226 
We've uploaded the code of the [leaf_gan_model](https://github.com/IyatomiLab/LeafGAN/blob/master/models/leaf_gan_model.py). Check it out!

**Comment by kasim0226** [comment]
Hi @huuquan1994 
Thank you for your great work!
