### ISSUE TITLE
LFLSeg_resnet101.pth is not found in google drive

### ISSUE THREAD

**Issue by wolverinex24** [IyatomiLab/LeafGAN#11]
there is no data in this drive link ```https://drive.google.com/drive/folders/1HqBYjUGXxl1eAkzhURoV5JAqWHvBvvTp?usp=sharing```

**Comment by huuquan1994** [comment]
@wolverinex24 

Sorry for the trouble! I've updated the download link to DropBox: [https://www.dropbox.com/scl/fi/h0t2dq5rtogxvp9ufglkj/LFLSeg_resnet101.pth?rlkey=noxfamgq5387y2hbvhjirrf7j&dl=0](https://www.dropbox.com/scl/fi/h0t2dq5rtogxvp9ufglkj/LFLSeg_resnet101.pth?rlkey=noxfamgq5387y2hbvhjirrf7j&dl=0)
